from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import DateTime, func
from sqlalchemy.orm import mapped_column, Mapped, declarative_base
from datetime import datetime

db = SQLAlchemy(model_class=declarative_base())

class Question(db.Model):
    __tablename__ = 'questions'
    question_id: Mapped[int] = mapped_column(primary_key=True)
    question: Mapped[str] = mapped_column(nullable=False)
    answer: Mapped[str] = mapped_column(nullable=False)
    question_time: Mapped[datetime] = mapped_column(DateTime(True), nullable=True, server_default=func.now())

def insert_question(question: Question) -> int:
    """
    Insert a single question+answer record to the database.

    :param question: The question record to insert.
    :return: A unique question id, generated by the database.
             It can be used to fetch the inserted record.
    """
    db.session.add(question)
    db.session.commit()

    return question.question_id
